version: "3.7"
services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-demo
    ports:
      - 8000:8000
    container_name: laravel-demo-app
    restart: unless-stopped
    working_dir: /var/www/html/blog
    volumes:
      - ./blog:/var/www/html/blog
    networks:
      - laravel-demo
  db:
    image: mysql:5.7
    container_name: laravel-demo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - laravel-demo

networks:
  laravel-demo:
    driver: bridge

volumes:
  db-volume:
